import { emotionOptions } from './schemas.js';
export class ConversationStateMachine { transition(current, event) { if (event === 'safety') return 'SAFETY_EXIT'; if (event === 'pause') return 'PAUSED'; if (event === 'resume') return current === 'PAUSED' ? 'CLARIFICATION' : current; if (event === 'complete') return 'SUMMARY'; const map = { PREPARE:'OPENING',OPENING:'TOPIC_SELECTION',TOPIC_SELECTION:'PERSON_A_EXPRESSION',PERSON_A_EXPRESSION:'PERSON_B_REFLECTION',PERSON_B_REFLECTION:'PERSON_B_EXPRESSION',PERSON_B_EXPRESSION:'PERSON_A_REFLECTION',PERSON_A_REFLECTION:'CLARIFICATION',CLARIFICATION:'COMMON_GROUND',COMMON_GROUND:'DIFFERENCE_EXPLORATION',DIFFERENCE_EXPLORATION:'DECISION',DECISION:'SUMMARY' }; return event === 'advance' ? (map[current] ?? current) : current; } }
const empty = (userId) => ({ userId,speakingDuration:0,turnCount:0,interruptionCount:0,unansweredPromptCount:0,selfExpressionCompleteness:0,clarificationOpportunities:0,reflectionOpportunities:0,unsureCount:0,unfinishedUtterances:0,assistanceRequested:0,topicOwnership:[] });
export class FairnessController {
  constructor(existing = {}) { this.participants = structuredClone(existing); }
  ensure(id) { return this.participants[id] ||= empty(id); }
  completeness(text) { let s=0; if(text.length>=12)s+=.25;if(/感じ|悲|怖|怒|寂|不安|嬉/.test(text))s+=.25;if(/から|ので|理由|背景/.test(text))s+=.25;if(/ほしい|望|したい|お願い/.test(text))s+=.25;return s; }
  recordTurn(id,text,meta={}) { const p=this.ensure(id),v=String(text);p.turnCount++;p.speakingDuration+=Number(meta.duration)||Math.max(1,Math.ceil(v.length/7));if(/分からない|わからない|うまく(言え|話せ)ない/.test(v))p.unsureCount++;if(/…$|\.\.\.$/.test(v)||meta.unfinished)p.unfinishedUtterances++;if(meta.interrupted)p.interruptionCount++;if(meta.answered===false)p.unansweredPromptCount++;if(meta.assistanceRequested)p.assistanceRequested++;p.selfExpressionCompleteness=Math.max(p.selfExpressionCompleteness,this.completeness(v));if(meta.topic&&!p.topicOwnership.includes(meta.topic))p.topicOwnership.push(meta.topic);return p; }
  supportLevel(id) { const p=this.ensure(id);if(p.unsureCount>=3||p.assistanceRequested>=2)return 4;if(p.unsureCount>=2||p.unfinishedUtterances>=2)return 3;if(p.unsureCount>=1||(p.selfExpressionCompleteness<.25&&p.turnCount>=2))return 2;return 1; }
  needsSupport(id) { const p=this.ensure(id);return p.unansweredPromptCount>0||p.interruptionCount>1||p.unsureCount>0||(p.turnCount>=2&&p.selfExpressionCompleteness<.25); }
  question(id) { const level=this.supportLevel(id);if(level===1)return{level,text:'今のことを、あなたはどう受け取りましたか？'};if(level===2)return{level,text:'いちばん強く残っている感じを、短い言葉で言えそうですか？'};if(level===3)return{level,text:'近いものを選べますか？選んだあと、理由があればあなたの言葉で教えてください。',options:emotionOptions};return{level,text:'今は話を続けたいですか？',options:['はい','いいえ','どちらとも言えない'],allowNote:true}; }
  snapshot(){return structuredClone(this.participants);}
}
export function detectSafety(text){return[/殺す|殴る|暴力|脅迫|逃げられない|監禁|自傷|死にたい|消えたい/].some(p=>p.test(String(text)))?{unsafe:true,message:'安全を優先するため、この対話はいったん停止できます。差し迫った危険がある場合は、その場を離れ、地域の緊急窓口や信頼できる人へ連絡してください。無理に二人だけで話し続ける必要はありません。'}:{unsafe:false};}
export function interventionDecision({fairness,speakerId,text,turnsSinceIntervention=99,repeated=false,stalled=false}){const safety=detectSafety(text);if(safety.unsafe)return{shouldIntervene:true,trigger:'safety',targetUserId:null,level:1,message:safety.message};if(turnsSinceIntervention<3)return{shouldIntervene:false,trigger:'cooldown',targetUserId:null,level:1,message:''};const other=Object.keys(fairness.participants).find(id=>id!==speakerId);if(other&&fairness.needsSupport(other)){const q=fairness.question(other);return{shouldIntervene:true,trigger:'expression_support',targetUserId:other,level:q.level,message:q.text,options:q.options};}if(repeated)return{shouldIntervene:true,trigger:'circular',targetUserId:null,level:1,message:'同じ点を別の言葉で確認しているようです。いったん「確認できたこと」と「まだ違うこと」を分けてもよいですか？'};if(stalled)return{shouldIntervene:true,trigger:'stalled',targetUserId:null,level:1,message:'今すぐ結論を出さなくても大丈夫です。続ける、短く休む、今日はここまで、のどれがよさそうですか？'};return{shouldIntervene:false,trigger:'none',targetUserId:null,level:1,message:''};}
export function symmetryAudit(evaluate,a,b){const norm=r=>({shouldIntervene:r.shouldIntervene,trigger:r.trigger,level:r.level});const forward=norm(evaluate(a,b)),reversed=norm(evaluate(b,a));return{passed:JSON.stringify(forward)===JSON.stringify(reversed),forward,reversed};}
