const phases = new Set(['PREPARE','OPENING','TOPIC_SELECTION','PERSON_A_EXPRESSION','PERSON_B_REFLECTION','PERSON_B_EXPRESSION','PERSON_A_REFLECTION','CLARIFICATION','COMMON_GROUND','DIFFERENCE_EXPLORATION','DECISION','SUMMARY','PAUSED','SAFETY_EXIT']);
export class ValidationError extends Error { constructor(message) { super(message); this.name = 'ValidationError'; this.status = 400; } }
export class AuthError extends Error { constructor(message = '認証が必要です', status = 401) { super(message); this.name = 'AuthError'; this.status = status; } }
export class ForbiddenError extends Error { constructor(message = 'アクセスできません') { super(message); this.name = 'ForbiddenError'; this.status = 403; } }
export class NotFoundError extends Error { constructor(message = '見つかりません') { super(message); this.name = 'NotFoundError'; this.status = 404; } }
export function assertString(value, name, { min = 1, max = 4000 } = {}) { if (typeof value !== 'string' || value.trim().length < min || value.length > max) throw new ValidationError(`${name} is invalid`); return value.trim(); }
export function validatePurpose(value) { const allowed = ['仲直り','不満を伝える','謝罪','相手を理解する','自分を理解してもらう','意思決定','すれ違い整理','その他']; if (!allowed.includes(value)) throw new ValidationError('purpose is invalid'); return value; }
export function validatePhase(value) { if (!phases.has(value)) throw new ValidationError('phase is invalid'); return value; }
export function validateConfidence(value) { if (value == null) return null; const n = Number(value); if (!Number.isFinite(n) || n < 0 || n > 1) throw new ValidationError('confidence is invalid'); return n; }
export function validateAnalysis(value) { const keys = ['events','perceptions','interpretations','emotions','needs','values','requests','uncertainties','possibleTopics']; if (!value || typeof value !== 'object' || keys.some((key) => !Array.isArray(value[key]) || value[key].some((x) => typeof x !== 'string'))) throw new ValidationError('analysis schema is invalid'); return Object.fromEntries(keys.map((key) => [key, value[key].slice(0, 20).map((x) => x.slice(0, 300))])); }
export function validateOpening(value) { if (!value || typeof value !== 'object' || !Array.isArray(value.topics)) throw new ValidationError('opening schema is invalid'); return { intro:assertString(value.intro,'intro',{max:500}), topics:value.topics.slice(0,4).map((x)=>assertString(x,'topic',{max:120})), firstQuestion:assertString(value.firstQuestion,'firstQuestion',{max:300}) }; }
export function validateSummary(value) { const keys=['confirmed','commonGround','differences','agreements','unresolved','futureTopics']; if (!value || typeof value !== 'object' || keys.some((key)=>!Array.isArray(value[key]) || value[key].some((x)=>typeof x!=='string'))) throw new ValidationError('summary schema is invalid'); return Object.fromEntries(keys.map((key)=>[key,value[key].slice(0,8).map((x)=>assertString(x,key,{max:400}))])); }
export function validateIntervention(value) { if (!value || typeof value !== 'object' || typeof value.shouldIntervene !== 'boolean') throw new ValidationError('intervention schema is invalid'); return { shouldIntervene: value.shouldIntervene, trigger: assertString(value.trigger || 'none', 'trigger', { max: 80 }), targetUserId: value.targetUserId ?? null, level: Math.min(4, Math.max(1, Number(value.level) || 1)), message: value.message ? assertString(value.message, 'message', { max: 800 }) : '' }; }
export const emotionOptions = ['悲しかった','怖かった','腹が立った','寂しかった','期待を裏切られた感じ','まだ分からない','どれにも当てはまらない'];
