-- PostgreSQL-compatible production schema. The zero-dependency development adapter uses data/app.json.
CREATE TABLE users (id text PRIMARY KEY, email text UNIQUE NOT NULL, password_hash text NOT NULL, display_name text NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE dialogue_sessions (id text PRIMARY KEY, title text NOT NULL, purpose text NOT NULL, status text NOT NULL, invite_code text UNIQUE NOT NULL, created_by text NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, completed_at timestamptz);
CREATE TABLE session_participants (id text PRIMARY KEY, session_id text NOT NULL REFERENCES dialogue_sessions(id) ON DELETE CASCADE, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL, joined_at timestamptz NOT NULL, UNIQUE(session_id,user_id));
CREATE TABLE private_preparations (id text PRIMARY KEY, session_id text NOT NULL REFERENCES dialogue_sessions(id) ON DELETE CASCADE, owner_user_id text NOT NULL REFERENCES users(id), raw_text text NOT NULL, guide_answers jsonb NOT NULL DEFAULT '{}', structured_analysis jsonb NOT NULL, analysis_source text, confirmed_analysis jsonb, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE share_candidates (id text PRIMARY KEY, session_id text NOT NULL REFERENCES dialogue_sessions(id) ON DELETE CASCADE, owner_user_id text NOT NULL REFERENCES users(id), generated_content text NOT NULL, edited_content text, approval_status text NOT NULL, shared_at timestamptz);
CREATE TABLE conversation_turns (id text PRIMARY KEY, session_id text NOT NULL REFERENCES dialogue_sessions(id) ON DELETE CASCADE, speaker_type text NOT NULL, speaker_user_id text REFERENCES users(id), source_type text NOT NULL, text text NOT NULL, transcript_confidence real, created_at timestamptz NOT NULL, edited_at timestamptz);
CREATE TABLE moderator_interventions (id text PRIMARY KEY, session_id text NOT NULL REFERENCES dialogue_sessions(id) ON DELETE CASCADE, trigger_type text NOT NULL, content text NOT NULL, reason_summary text NOT NULL, prompt_version text NOT NULL, scaffolding_level int NOT NULL, options jsonb, created_at timestamptz NOT NULL);
CREATE TABLE conversation_states (session_id text PRIMARY KEY REFERENCES dialogue_sessions(id) ON DELETE CASCADE, current_phase text NOT NULL, active_topic text, structured_state jsonb NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE fairness_states (session_id text PRIMARY KEY REFERENCES dialogue_sessions(id) ON DELETE CASCADE, per_participant_state jsonb NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE session_summaries (id text PRIMARY KEY, session_id text NOT NULL REFERENCES dialogue_sessions(id) ON DELETE CASCADE, common_ground jsonb NOT NULL, differences jsonb NOT NULL, agreements jsonb NOT NULL, unresolved jsonb NOT NULL, future_topics jsonb NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE historical_reference_approvals (id text PRIMARY KEY, session_id text NOT NULL REFERENCES dialogue_sessions(id) ON DELETE CASCADE, owner_user_id text NOT NULL REFERENCES users(id), source_session_id text NOT NULL REFERENCES dialogue_sessions(id), proposed_reference text NOT NULL, approval_status text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE ai_request_metadata (id text PRIMARY KEY, session_id text NOT NULL REFERENCES dialogue_sessions(id) ON DELETE CASCADE, provider text NOT NULL, model text, operation_type text NOT NULL, prompt_version text NOT NULL, latency int NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL);
CREATE INDEX conversation_turns_session_created_idx ON conversation_turns(session_id,created_at);
CREATE INDEX private_preparations_owner_idx ON private_preparations(session_id,owner_user_id);
