import { randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import { FairnessController, ConversationStateMachine, interventionDecision } from './domain/mediation.js';
import { approvedHistoricalReferences, ownPrivatePreparations, redactSession, requireParticipant, visibleShares } from './domain/privacy.js';
import { aiMetadata } from './infra/ai.js';
import { assertString, AuthError, ForbiddenError, NotFoundError, validateAnalysis, validateConfidence, validatePurpose } from './domain/schemas.js';
import { PROMPT_VERSION } from './domain/policy.js';

const now=()=>new Date().toISOString();
const id=(prefix)=>`${prefix}_${randomUUID()}`;
const code=()=>randomBytes(5).toString('base64url').toUpperCase();
export function hashPassword(password){assertString(password,'password',{min:10,max:200});const salt=randomBytes(16);const hash=scryptSync(password,salt,64);return`${salt.toString('hex')}:${hash.toString('hex')}`;}
export function verifyPassword(password,stored){try{const[s,h]=stored.split(':');return timingSafeEqual(scryptSync(password,Buffer.from(s,'hex'),64),Buffer.from(h,'hex'));}catch{return false;}}

export class AppService {
  constructor(store,ai,{emit=()=>{}}={}){this.store=store;this.ai=ai;this.emit=emit;this.machine=new ConversationStateMachine();}
  async register({email,password,displayName}){email=assertString(email,'email',{max:254}).toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new AuthError('メールアドレスが不正です',400);displayName=assertString(displayName,'displayName',{max:50});return this.store.mutate((db)=>{if(db.users.some((u)=>u.email===email))throw new AuthError('登録済みです',409);const user={id:id('usr'),email,passwordHash:hashPassword(password),displayName,createdAt:now(),updatedAt:now()};db.users.push(user);return this.publicUser(user);});}
  login({email,password}){const user=this.store.snapshot().users.find((u)=>u.email===String(email).toLowerCase());if(!user||!verifyPassword(String(password),user.passwordHash))throw new AuthError('認証情報が一致しません');return this.publicUser(user);}
  publicUser(u){return{id:u.id,email:u.email,displayName:u.displayName};}
  user(id){const u=this.store.snapshot().users.find((x)=>x.id===id);if(!u)throw new AuthError();return this.publicUser(u);}
  async createSession(userId,{title,purpose}){title=assertString(title,'title',{max:100});purpose=validatePurpose(purpose);return this.store.mutate((db)=>{const session={id:id('ses'),title,purpose,status:'prepare',inviteCode:code(),createdBy:userId,createdAt:now(),updatedAt:now(),completedAt:null};db.sessions.push(session);db.participants.push({id:id('par'),sessionId:session.id,userId,role:'A',joinedAt:now()});db.conversationStates.push({sessionId:session.id,currentPhase:'PREPARE',activeTopic:null,structuredState:{},updatedAt:now()});db.fairnessStates.push({sessionId:session.id,perParticipantState:{[userId]:new FairnessController().ensure(userId)},updatedAt:now()});return redactSession(db,session,userId);});}
  listSessions(userId){const db=this.store.snapshot();return db.participants.filter((p)=>p.userId===userId).map((p)=>redactSession(db,db.sessions.find((s)=>s.id===p.sessionId),userId));}
  getSession(userId,sessionId){const db=this.store.snapshot();const{session}=requireParticipant(db,sessionId,userId);const people=db.participants.filter((x)=>x.sessionId===sessionId),preps=db.privatePreparations.filter((x)=>x.sessionId===sessionId);return{session:redactSession(db,session,userId),preparations:ownPrivatePreparations(db,sessionId,userId),readiness:{participants:people.length,prepared:preps.length,confirmed:preps.filter((x)=>x.confirmedAnalysis).length},shares:visibleShares(db,sessionId,userId),turns:db.turns.filter((x)=>x.sessionId===sessionId),interventions:db.interventions.filter((x)=>x.sessionId===sessionId),state:db.conversationStates.find((x)=>x.sessionId===sessionId),summary:db.summaries.find((x)=>x.sessionId===sessionId)||null};}
  async joinSession(userId,inviteCode){return this.store.mutate((db)=>{const session=db.sessions.find((s)=>s.inviteCode===String(inviteCode).toUpperCase());if(!session)throw new NotFoundError('参加コードが見つかりません');if(db.participants.some((p)=>p.sessionId===session.id&&p.userId===userId))return redactSession(db,session,userId);if(db.participants.filter((p)=>p.sessionId===session.id).length>=2)throw new ForbiddenError('このセッションは満員です');db.participants.push({id:id('par'),sessionId:session.id,userId,role:'B',joinedAt:now()});const fs=db.fairnessStates.find((x)=>x.sessionId===session.id);fs.perParticipantState[userId]=new FairnessController().ensure(userId);fs.updatedAt=now();return redactSession(db,session,userId);});}
  async prepare(userId,sessionId,{rawText,guides={}}){requireParticipant(this.store.snapshot(),sessionId,userId);rawText=assertString(rawText,'rawText',{max:10000});const started=Date.now();let analysis,status='success';try{analysis=await this.ai.analyzePrivateInput(rawText);}catch(error){console.warn('AI private analysis fallback',error.name,error.message);status='fallback';analysis=await import('./infra/ai.js').then(({MockAIProvider})=>new MockAIProvider().analyzePrivateInput(rawText));}return this.store.mutate((db)=>{requireParticipant(db,sessionId,userId);const previous=db.privatePreparations.find((x)=>x.sessionId===sessionId&&x.ownerUserId===userId);const value={id:previous?.id||id('prep'),sessionId,ownerUserId:userId,rawText,guideAnswers:guides,structuredAnalysis:analysis,analysisSource:status==='fallback'?'fallback':this.ai.name,confirmedAnalysis:null,createdAt:previous?.createdAt||now(),updatedAt:now()};if(previous)Object.assign(previous,value);else db.privatePreparations.push(value);for(const content of [...analysis.emotions,...analysis.needs,...analysis.requests].slice(0,6)){if(!db.shareCandidates.some((x)=>x.sessionId===sessionId&&x.ownerUserId===userId&&x.generatedContent===content))db.shareCandidates.push({id:id('shr'),sessionId,ownerUserId:userId,generatedContent:content,editedContent:null,approvalStatus:'pending',sharedAt:null});}db.aiRequests.push({id:id('air'),sessionId,...aiMetadata(this.ai,'private_analysis',status,started),createdAt:now()});return value;});}
  async confirmAnalysis(userId,sessionId,analysis){analysis=validateAnalysis(analysis);const result=await this.store.mutate((db)=>{requireParticipant(db,sessionId,userId);const prep=db.privatePreparations.find((x)=>x.sessionId===sessionId&&x.ownerUserId===userId);if(!prep)throw new NotFoundError();prep.confirmedAnalysis=analysis;prep.updatedAt=now();return prep;});this.emit(sessionId,'preparation',{userId});return result;}
  async createOpening(userId,sessionId){const db=this.store.snapshot();const {session}=requireParticipant(db,sessionId,userId);const participants=db.participants.filter((x)=>x.sessionId===sessionId);if(participants.length!==2||participants.some((p)=>!db.privatePreparations.some((x)=>x.sessionId===sessionId&&x.ownerUserId===p.userId&&x.confirmedAnalysis)))throw new ForbiddenError('二人の事前整理と確認が必要です');const existing=db.conversationStates.find((x)=>x.sessionId===sessionId).structuredState.opening;if(existing)return existing;const input={session:{title:session.title,purpose:session.purpose},sharedItems:db.shareCandidates.filter((x)=>x.sessionId===sessionId&&x.approvalStatus==='shared').map((x)=>x.editedContent||x.generatedContent).slice(0,8)};const started=Date.now();let opening,status='success';try{opening=await this.ai.generateOpening(input);}catch(error){console.warn('AI opening fallback',error.name,error.message);status='fallback';opening=await import('./infra/ai.js').then(({MockAIProvider})=>new MockAIProvider().generateOpening(input));}opening={...opening,source:status==='fallback'?'fallback':this.ai.name};const result=await this.store.mutate((draft)=>{requireParticipant(draft,sessionId,userId);const state=draft.conversationStates.find((x)=>x.sessionId===sessionId);if(state.structuredState.opening)return state.structuredState.opening;state.structuredState.opening=opening;state.currentPhase='OPENING';state.updatedAt=now();const active=draft.sessions.find((x)=>x.id===sessionId);active.status='active';active.updatedAt=now();draft.aiRequests.push({id:id('air'),sessionId,...aiMetadata(this.ai,'opening',status,started),createdAt:now()});return opening;});this.emit(sessionId,'opening',{ready:true});return result;}
  async approveShare(userId,sessionId,candidateId,{action,editedContent}){if(!['share','edit','reject'].includes(action))throw new ForbiddenError('操作が不正です');return this.store.mutate((db)=>{requireParticipant(db,sessionId,userId);const c=db.shareCandidates.find((x)=>x.id===candidateId&&x.sessionId===sessionId&&x.ownerUserId===userId);if(!c)throw new NotFoundError();c.approvalStatus=action==='reject'?'rejected':'shared';c.editedContent=action==='edit'?assertString(editedContent,'editedContent',{max:1000}):c.editedContent;c.sharedAt=c.approvalStatus==='shared'?now():null;if(c.sharedAt)this.emit(sessionId,'share',{...c,generatedContent:undefined});return c;});}
  async addTurn(userId,sessionId,{text,sourceType='text',transcriptConfidence=null,duration=0}){text=assertString(text,'text',{max:4000});transcriptConfidence=validateConfidence(transcriptConfidence);const db0=this.store.snapshot();requireParticipant(db0,sessionId,userId);if(sourceType==='audio'&&(transcriptConfidence==null||transcriptConfidence<.65))return{requiresConfirmation:true,text,transcriptConfidence,fallback:'text'};const result=await this.store.mutate((db)=>{const participant=requireParticipant(db,sessionId,userId).participant;const phase=db.conversationStates.find((x)=>x.sessionId===sessionId).currentPhase;if(['PAUSED','SAFETY_EXIT','SUMMARY'].includes(phase))throw new ForbiddenError('この対話は現在投稿できません');const turn={id:id('turn'),sessionId,speakerType:'user',speakerUserId:userId,sourceType,text,transcriptConfidence,createdAt:now(),editedAt:null};db.turns.push(turn);const fs=db.fairnessStates.find((x)=>x.sessionId===sessionId);const fairness=new FairnessController(fs.perParticipantState);fairness.recordTurn(userId,text,{duration});fs.perParticipantState=fairness.snapshot();fs.updatedAt=now();const lastIntervention=db.interventions.filter((x)=>x.sessionId===sessionId).at(-1);const since=lastIntervention?db.turns.filter((x)=>x.sessionId===sessionId&&x.createdAt>lastIntervention.createdAt).length:99;const recent=db.turns.filter((x)=>x.sessionId===sessionId).slice(-3).map((x)=>x.text);const decision=interventionDecision({fairness,speakerId:userId,text,turnsSinceIntervention:since,repeated:recent.length===3&&new Set(recent.map((x)=>x.slice(0,20))).size===1});return{turn,decision,participant};});this.emit(sessionId,'turn',result.turn);if(result.decision.shouldIntervene)await this.createIntervention(sessionId,result.decision);return result;}
  async editTurn(userId,sessionId,turnId,text){return this.store.mutate((db)=>{requireParticipant(db,sessionId,userId);const turn=db.turns.find((x)=>x.id===turnId&&x.sessionId===sessionId&&x.speakerUserId===userId);if(!turn)throw new NotFoundError();turn.text=assertString(text,'text',{max:4000});turn.editedAt=now();this.emit(sessionId,'turn-edited',turn);return turn;});}
  async createIntervention(sessionId,candidate){const started=Date.now(),snapshot=this.store.snapshot(),session=snapshot.sessions.find((x)=>x.id===sessionId),recentTurns=snapshot.turns.filter((x)=>x.sessionId===sessionId).slice(-8).map(({speakerType,speakerUserId,text})=>({speakerType,speakerUserId,text}));let content,status='success';if(candidate.trigger==='safety'){content=candidate.message;status='safety_rule';}else try{content=await this.ai.generateModeratorMessage({candidate,session:{title:session.title,purpose:session.purpose},recentTurns});}catch{content=candidate.message;status='fallback';}return this.store.mutate((db)=>{const intervention={id:id('int'),sessionId,triggerType:candidate.trigger,content,reasonSummary:candidate.trigger,promptVersion:PROMPT_VERSION,scaffoldingLevel:candidate.level,options:candidate.options||null,createdAt:now()};db.interventions.push(intervention);db.turns.push({id:id('turn'),sessionId,speakerType:'moderator',speakerUserId:null,sourceType:'text',text:content,createdAt:intervention.createdAt});const state=db.conversationStates.find((x)=>x.sessionId===sessionId);if(candidate.trigger==='safety')state.currentPhase='SAFETY_EXIT';db.aiRequests.push({id:id('air'),sessionId,...aiMetadata(this.ai,'moderator_message',status,started),createdAt:now()});this.emit(sessionId,'intervention',intervention);return intervention;});}
  async setState(userId,sessionId,event){return this.store.mutate((db)=>{requireParticipant(db,sessionId,userId);const state=db.conversationStates.find((x)=>x.sessionId===sessionId);if(['SAFETY_EXIT','SUMMARY'].includes(state.currentPhase))throw new ForbiddenError('この対話は再開できません');state.currentPhase=this.machine.transition(state.currentPhase,event);state.updatedAt=now();this.emit(sessionId,'state',state);return state;});}
  async complete(userId,sessionId){const db=this.store.snapshot();requireParticipant(db,sessionId,userId);const started=Date.now(),turns=db.turns.filter((x)=>x.sessionId===sessionId).map(({text,speakerType,speakerUserId})=>({text,speakerType,speakerUserId}));let summary,status='success';try{summary=await this.ai.generateSummary(turns);}catch(error){console.warn('AI summary fallback',error.name,error.message);status='fallback';summary=await import('./infra/ai.js').then(({MockAIProvider})=>new MockAIProvider().generateSummary(turns));}return this.store.mutate((draft)=>{const value={id:id('sum'),sessionId,...summary,source:status==='fallback'?'fallback':this.ai.name,createdAt:now()};draft.summaries.push(value);const session=draft.sessions.find((x)=>x.id===sessionId);session.status='completed';session.completedAt=now();draft.conversationStates.find((x)=>x.sessionId===sessionId).currentPhase='SUMMARY';draft.aiRequests.push({id:id('air'),sessionId,...aiMetadata(this.ai,'session_summary',status,started),createdAt:now()});this.emit(sessionId,'summary',value);return value;});}
  async proposeHistory(userId,sessionId,{sourceSessionId,proposedReference}){return this.store.mutate((db)=>{requireParticipant(db,sessionId,userId);requireParticipant(db,sourceSessionId,userId);const value={id:id('hist'),sessionId,ownerUserId:userId,sourceSessionId,proposedReference:assertString(proposedReference,'proposedReference',{max:1000}),approvalStatus:'pending',createdAt:now()};db.historyApprovals.push(value);return value;});}
  async approveHistory(userId,sessionId,approvalId,approved){return this.store.mutate((db)=>{const x=db.historyApprovals.find((v)=>v.id===approvalId&&v.sessionId===sessionId&&v.ownerUserId===userId);if(!x)throw new NotFoundError();x.approvalStatus=approved?'approved':'rejected';return x;});}
  historicalContext(userId,sessionId){const db=this.store.snapshot();requireParticipant(db,sessionId,userId);return approvedHistoricalReferences(db,sessionId);}
  async deleteSession(userId,sessionId){return this.store.mutate((db)=>{const s=db.sessions.find((x)=>x.id===sessionId);if(!s)throw new NotFoundError();if(s.createdBy!==userId)throw new ForbiddenError('作成者のみ削除できます');for(const key of ['participants','privatePreparations','shareCandidates','turns','interventions','conversationStates','fairnessStates','summaries','historyApprovals','aiRequests'])db[key]=db[key].filter((x)=>x.sessionId!==sessionId);db.sessions=db.sessions.filter((x)=>x.id!==sessionId);this.emit(sessionId,'deleted',{});return{deleted:true};});}
}
